name: Garmin CN data sync to global region

on:
  workflow_dispatch:
  schedule:
    - cron: '0 14 * * *'
  watch:
    types: started

jobs:
  sync:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: run script
      env:
        GARMIN_EMAIL: ${{ secrets.GARMIN_EMAIL }}
        GARMIN_PASSWORD: ${{ secrets.GARMIN_PASSWORD }}
        GARMIN_GLOBAL_EMAIL: ${{ secrets.GARMIN_GLOBAL_EMAIL }}
        GARMIN_GLOBAL_PASSWORD: ${{ secrets.GARMIN_GLOBAL_PASSWORD }}
      run: |
        python GarminSync.py
